files = [ 'stream/assets/*' ]

[meta]
'stream/props/decals_kpri_sol.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/kpri_props_v2.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/rm_cup01data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/rmcap_la.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/RM-PoussetteData.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/tetley_chicagohood1.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/tag/RM-Tag-Data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/tag/Rm-TagData-2.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/park/mickystudio_park11.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/park/mickystudio_park12.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/park/mickystudio_park13.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/park/mickystudio_park14.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/park/rm_kidspark02data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/park/rm_kidsparkdata.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/road/Rm-DataRoad4444.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/fence/def_props.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/fence/fence4data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/fence/RM-FenceBrick-Data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/basket/kpri.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/basket/RmBasketRed-data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/ground/Rm-GroundD-Data.ytyp' = 'DLC_ITYP_REQUEST'
'stream/props/building/rmbatlcop-data.ytyp' = 'DLC_ITYP_REQUEST'
